In [4]:
import pandas as pd

In [29]:
XLY = pd.read_csv("Consumer Discretionary (XLY).csv")

In [30]:
XLP = pd.read_csv("Consumer Staples Select Sector SPDR (XLP).csv")

In [31]:
FDN = pd.read_csv("DJ Internet Index Fund (FDN).csv")

In [32]:
XLE = pd.read_csv("Energy Select Sector SPDR (XLE).csv")

In [33]:
XLF = pd.read_csv("Financial Select Sector SPDR Fund (XLF).csv")

In [34]:
XLV = pd.read_csv("Health Care Select Sector SPDR (XLV).csv")

In [35]:
XLI = pd.read_csv("Industrial Select Sector SPDR (XLI).csv")

In [36]:
IGF = pd.read_csv("iShares Global Infrastructure ETF (IGF).csv")

In [37]:
IBB = pd.read_csv("iShares Nasdaq Biotechnology ETF (IBB).csv")

In [38]:
IYT = pd.read_csv("iShares Transportation Average ETF (IYT).csv")

In [39]:
ITB = pd.read_csv("iShares U.S. Home Construction ETF (ITB).csv")

In [40]:
IYZ = pd.read_csv("iShares US Telecommunications ETF (IYZ).csv")

In [41]:
GDX = pd.read_csv("Market Vectors TR Gold Miners (GDX).csv")

In [42]:
XLB = pd.read_csv("Materials Select Sector SPDR (XLB).csv")

In [44]:
KBE = pd.read_csv("SPDR S&P Bank ETF (KBE).csv")

In [45]:
XLK = pd.read_csv("Technology Select Sector SPDR (XLK).csv")

In [46]:
XLU = pd.read_csv("Utilities Select Sector SPDR (XLU).csv")

In [47]:
VOX = pd.read_csv("Vanguard Communication Services ETF (VOX).csv")

In [48]:
VCR = pd.read_csv("Vanguard Consumer Discretionary (VCR).csv")

In [49]:
VDC = pd.read_csv("Vanguard Consumer Staples ETF (VDC).csv")

In [50]:
VDE = pd.read_csv("Vanguard Energy ETF (VDE).csv")

In [51]:
VFH = pd.read_csv("Vanguard Financials ETF (VFH).csv")

In [52]:
VHT = pd.read_csv("Vanguard Health Care ETF (VHT).csv")

In [53]:
VIS = pd.read_csv("Vanguard Industrials ETF (VIS).csv")

In [54]:
VGT = pd.read_csv("Vanguard Information Tech ETF (VGT).csv")

In [55]:
VNQ = pd.read_csv("Vanguard REIT ETF (VNQ).csv")

In [56]:
VPU = pd.read_csv("Vanguard Utilities ETF (VPU).csv")

In [71]:
DATASETS_ETF = pd.concat([XLY, VCR, XLP, VDC, XLE, VDE, XLF, VFH, KBE, XLV, IBB, VHT, XLI, VIS, IYT, XLK, VGT, FDN, XLB, GDX, ITB, VNQ, VOX, IYZ, XLU, VPU, IGF], axis=0)

In [73]:
del DATASETS_ETG

In [57]:
DATASETS_ETF = pd.read_csv("DATASETS_etf.csv")

In [76]:
DATASETS_ETF.reset_index(inplace=True, drop=True)

In [77]:
DATASETS_ETF

,Date,NOMBRE,AREA,TIPO,SECTOR,PRECIO,PRECIO NORMALIADO MAX,PRECIO NORMALIADO MIN,PRECIO SEMANAL,RENTABILIDAD SEMANAL,...,PRECIO LUSTRO,RENTABILIDAD LUSTRO,PRECIO SEMESTRAL A,A 6 MESES,PRECIO ANIO A,A 1 ANIO,PRECIO 2 ANIO A,A 2 ANIOS,PRECIO LUSTRO A,A 5 ANIOS
0,2021-12-26,Consumer Discretionary (XLY),EEUU,ETF,CONSUMO,204.44,966.985148,12.526961,203.19,0.006152,...,81.40,1.511548,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-12-19,Consumer Discretionary (XLY),EEUU,ETF,CONSUMO,203.19,961.072746,12.450368,195.29,0.040453,...,82.45,1.464403,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-12-12,Consumer Discretionary (XLY),EEUU,ETF,CONSUMO,195.29,923.706366,11.966299,204.99,-0.047319,...,82.69,1.361712,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-12-05,Consumer Discretionary (XLY),EEUU,ETF,CONSUMO,204.99,969.586605,12.560662,199.65,0.026747,...,84.31,1.431384,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-11-28,Consumer Discretionary (XLY),EEUU,ETF,CONSUMO,199.65,944.328824,12.233456,204.07,-0.021659,...,81.44,1.451498,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27197,2008-01-13,iShares Global Infrastructure ETF (IGF),EEUU,ETF,SERVICIOS PUBLICOS,46.15,925.591657,2.169723,48.48,-0.048061,...,NaN,NaN,44.52,-0.035320,27.35,-0.407367,35.26,-0.235970,36.14,-0.216901
27198,2008-01-06,iShares Global Infrastructure ETF (IGF),EEUU,ETF,SERVICIOS PUBLICOS,48.48,972.322503,2.279267,49.26,-0.015834,...,NaN,NaN,46.15,-0.048061,28.95,-0.402847,35.67,-0.264233,36.10,-0.255363
27199,2007-12-30,iShares Global Infrastructure ETF (IGF),EEUU,ETF,SERVICIOS PUBLICOS,49.26,987.966306,2.315938,49.86,-0.012034,...,NaN,NaN,48.48,-0.015834,30.21,-0.386724,34.08,-0.308161,36.19,-0.265327
27200,2007-12-23,iShares Global Infrastructure ETF (IGF),EEUU,ETF,SERVICIOS PUBLICOS,49.86,1000.000000,2.344147,49.83,0.000602,...,NaN,NaN,49.26,-0.012034,28.28,-0.432812,34.40,-0.310068,35.11,-0.295828
27201,2007-12-16,iShares Global Infrastructure ETF (IGF),EEUU,ETF,SERVICIOS PUBLICOS,49.83,999.398315,2.342736,NaN,NaN,...,NaN,NaN,49.86,0.000602,29.35,-0.410997,34.50,-0.307646,35.44,-0.288782

In [11]:
del SP500

NameError: name 'SP500' is not defined

In [12]:
DAX = pd.read_csv("DAX.csv")

In [14]:
DOW = pd.read_csv("DOW JONES INDUSTRIAL.csv")

In [15]:
EURO = pd.read_csv("EURONEXT 100.csv")

In [16]:
GOLD = pd.read_csv("GOLD SPOT US DOLLAR.csv")

In [17]:
IBEX = pd.read_csv("IBEX 35.csv")

In [19]:
NASDAQ = pd.read_csv("NASDAQ 100.csv")

In [20]:
NYSE = pd.read_csv("NYSE COMPOSITE.csv")

In [22]:
SP500 = pd.read_csv("S&P 500.csv")

In [23]:
DATASETS_INDEX = pd.concat([DAX, DOW, EURO, GOLD, IBEX, NASDAQ, NYSE, SP500], axis=0)

In [24]:
DATASETS_INDEX.reset_index(inplace=True, drop=True)

In [25]:
DATASETS_INDEX

,Date,NOMBRE,AREA,TIPO,SECTOR,PRECIO,PRECIO NORMALIADO MAX,PRECIO NORMALIADO MIN,PRECIO SEMANAL,RENTABILIDAD SEMANAL,...,PRECIO LUSTRO,RENTABILIDAD LUSTRO,PRECIO SEMESTRAL A,A 6 MESES,PRECIO ANIO A,A 1 ANIO,PRECIO 2 ANIO A,A 2 ANIOS,PRECIO LUSTRO A,A 5 ANIOS
0,2022-03-06,DAX,EUROPA,INDICE,NaN,13087.13,809.848657,13.981976,13094.54,-0.000566,...,11963.18,0.093951,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-02-27,DAX,EUROPA,INDICE,NaN,13094.54,810.307197,13.989893,14567.23,-0.101096,...,12027.36,0.088729,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022-02-20,DAX,EUROPA,INDICE,NaN,14567.23,901.439173,15.563280,15042.51,-0.031596,...,11804.03,0.234090,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022-02-13,DAX,EUROPA,INDICE,NaN,15042.51,930.850119,16.071058,15425.12,-0.024804,...,11757.02,0.279449,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022-02-06,DAX,EUROPA,INDICE,NaN,15425.12,954.526524,16.479829,15099.56,0.021561,...,11666.97,0.322119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17317,1970-02-01,S&P 500,EEUU,INDICE,NaN,86.33,18.113038,1.384825,85.02,0.015408,...,NaN,NaN,86.54,0.002433,96.93,0.122785,104.86,0.214641,78.63,-0.089193
17318,1970-01-25,S&P 500,EEUU,INDICE,NaN,85.02,17.838185,1.363811,89.37,-0.048674,...,NaN,NaN,86.33,0.015408,95.88,0.127735,104.16,0.225124,76.98,-0.094566
17319,1970-01-18,S&P 500,EEUU,INDICE,NaN,89.37,18.750865,1.433590,90.92,-0.017048,...,NaN,NaN,85.02,-0.048674,94.88,0.061654,103.65,0.159785,72.98,-0.183395
17320,1970-01-11,S&P 500,EEUU,INDICE,NaN,90.92,19.076074,1.458454,92.40,-0.016017,...,NaN,NaN,89.37,-0.017048,93.03,0.023207,103.39,0.137154,70.96,-0.219534
17321,1970-01-04,S&P 500,EEUU,INDICE,NaN,92.40,19.386595,1.482194,NaN,NaN,...,NaN,NaN,90.92,-0.016017,92.19,-0.002273,103.47,0.119805,72.61,-0.214177

In [26]:
DATASETS_INDEX.drop(['PRECIO SEMANAL', 'PRECIO MENSUAL', 'PRECIO ANUAL','PRECIO BIANUAL','PRECIO LUSTRO','PRECIO LUSTRO A','PRECIO 2 ANIO A','PRECIO ANIO A','PRECIO SEMESTRAL A'],inplace=True, axis=1)

In [101]:
DATASETS_ETF.drop(['PRECIO SEMANAL', 'PRECIO MENSUAL', 'PRECIO ANUAL','PRECIO BIANUAL','PRECIO LUSTRO','PRECIO LUSTRO A','PRECIO 2 ANIO A','PRECIO ANIO A','PRECIO SEMESTRAL A'],inplace=True, axis=1)

In [107]:
DATASETS_INDEX.groupby('NOMBRE')['RENTABILIDAD ANUAL'].mean()

NOMBRE
DAX                             0.105548
DOW JONES INDUSTRIAL AVERAGE    0.089522
EURONEXT 100                    0.030005
GOLD SPOT US DOLLAR             0.107119
IBEX 35                         0.067781
NADAQ 100                       0.176441
NYSE COMPOSITE                  0.084011
S&P500                          0.093327
Name: RENTABILIDAD ANUAL, dtype: float64

In [106]:
DATASETS_ETF[DATASETS_ETF['RENTABILIDAD SEMANAL']<-0.10]

,Date,NOMBRE,AREA,TIPO,SECTOR,PRECIO,PRECIO NORMALIADO MAX,PRECIO NORMALIADO MIN,RENTABILIDAD SEMANAL,RENTABILIDAD MENSUAL,RENTABILIDAD ANUAL,RENTABILIDAD BIANUAL,RENTABILIDAD LUSTRO,A 6 MESES,A 1 ANIO,A 2 ANIOS,A 5 ANIOS
93,2020-03-15,Consumer Discretionary (XLY),EEUU,ETF,CONSUMO,87.81,415.334405,5.380515,-0.141642,-0.326094,-0.213665,-0.123478,0.143806,0.116615,0.895570,NaN,NaN
94,2020-03-08,Consumer Discretionary (XLY),EEUU,ETF,CONSUMO,102.30,483.870968,6.268382,-0.107719,-0.223176,-0.075045,-0.027382,0.361096,-0.141642,0.630205,NaN,NaN
96,2020-02-23,Consumer Discretionary (XLY),EEUU,ETF,CONSUMO,115.83,547.866805,7.097426,-0.111051,-0.075726,0.042574,0.124017,0.524681,-0.010187,0.391263,NaN,NaN
688,2008-10-19,Consumer Discretionary (XLY),EEUU,ETF,CONSUMO,19.42,91.855075,1.189951,-0.126799,-0.336068,-0.468673,-0.475985,-0.332417,0.183316,0.454686,0.800206,2.260041
690,2008-10-05,Consumer Discretionary (XLY),EEUU,ETF,CONSUMO,22.13,104.673162,1.356005,-0.147206,-0.290705,-0.414860,-0.395850,-0.246253,0.004971,0.256213,0.552643,1.746950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26562,2020-03-15,iShares Global Infrastructure ETF (IGF),EEUU,ETF,SERVICIOS PUBLICOS,30.20,605.695949,1.419840,-0.160411,-0.391252,-0.320738,-0.280095,-0.285376,0.130132,0.474834,NaN,NaN
26563,2020-03-08,iShares Global Infrastructure ETF (IGF),EEUU,ETF,SERVICIOS PUBLICOS,35.97,721.419976,1.691114,-0.199421,-0.276840,-0.193317,-0.168131,-0.107887,-0.160411,0.258271,NaN,NaN
26565,2020-02-23,iShares Global Infrastructure ETF (IGF),EEUU,ETF,SERVICIOS PUBLICOS,44.14,885.278781,2.075223,-0.110260,-0.089897,0.005467,0.037612,0.043499,0.017898,-0.026053,NaN,NaN
27159,2008-10-05,iShares Global Infrastructure ETF (IGF),EEUU,ETF,SERVICIOS PUBLICOS,26.49,531.287605,1.245416,-0.224985,-0.307270,NaN,NaN,NaN,0.087203,0.280483,0.325406,0.466969
27160,2008-09-28,iShares Global Infrastructure ETF (IGF),EEUU,ETF,SERVICIOS PUBLICOS,34.18,685.519454,1.606958,-0.100526,-0.104063,NaN,NaN,NaN,-0.224985,-0.050322,0.006437,0.113809

In [104]:
DATASETS_ETF.to_csv("DATASETS_etf.csv", index = False)

In [27]:
DATASETS_INDEX.to_csv("DATASETS_indice.csv", index = False)

In [58]:
DATASETS_ANALISIS = pd.concat([DATASETS_INDEX, DATASETS_ETF], axis=0)

In [59]:
DATASETS_ANALISIS

,Date,NOMBRE,AREA,TIPO,SECTOR,PRECIO,PRECIO NORMALIADO MAX,PRECIO NORMALIADO MIN,RENTABILIDAD SEMANAL,RENTABILIDAD MENSUAL,RENTABILIDAD ANUAL,RENTABILIDAD BIANUAL,RENTABILIDAD LUSTRO,A 6 MESES,A 1 ANIO,A 2 ANIOS,A 5 ANIOS
0,2022-03-06,DAX,EUROPA,INDICE,NaN,13087.13,809.848657,13.981976,-0.000566,-0.151570,-0.097588,0.417571,0.093951,NaN,NaN,NaN,NaN
1,2022-02-27,DAX,EUROPA,INDICE,NaN,13094.54,810.307197,13.989893,-0.101096,-0.132787,-0.059347,0.134525,0.088729,NaN,NaN,NaN,NaN
2,2022-02-20,DAX,EUROPA,INDICE,NaN,14567.23,901.439173,15.563280,-0.031596,-0.049071,0.056646,0.225130,0.234090,NaN,NaN,NaN,NaN
3,2022-02-13,DAX,EUROPA,INDICE,NaN,15042.51,930.850119,16.071058,-0.024804,-0.035976,0.074985,0.107751,0.279449,NaN,NaN,NaN,NaN
4,2022-02-06,DAX,EUROPA,INDICE,NaN,15425.12,954.526524,16.479829,0.021561,-0.028843,0.097882,0.122299,0.322119,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27197,2008-01-13,iShares Global Infrastructure ETF (IGF),EEUU,ETF,SERVICIOS PUBLICOS,46.15,925.591657,2.169723,-0.048061,-0.073851,NaN,NaN,NaN,-0.035320,-0.407367,-0.235970,-0.216901
27198,2008-01-06,iShares Global Infrastructure ETF (IGF),EEUU,ETF,SERVICIOS PUBLICOS,48.48,972.322503,2.279267,-0.015834,NaN,NaN,NaN,NaN,-0.048061,-0.402847,-0.264233,-0.255363
27199,2007-12-30,iShares Global Infrastructure ETF (IGF),EEUU,ETF,SERVICIOS PUBLICOS,49.26,987.966306,2.315938,-0.012034,NaN,NaN,NaN,NaN,-0.015834,-0.386724,-0.308161,-0.265327
27200,2007-12-23,iShares Global Infrastructure ETF (IGF),EEUU,ETF,SERVICIOS PUBLICOS,49.86,1000.000000,2.344147,0.000602,NaN,NaN,NaN,NaN,-0.012034,-0.432812,-0.310068,-0.295828
27201,2007-12-16,iShares Global Infrastructure ETF (IGF),EEUU,ETF,SERVICIOS PUBLICOS,49.83,999.398315,2.342736,NaN,NaN,NaN,NaN,NaN,0.000602,-0.410997,-0.307646,-0.288782

In [60]:
DATASETS_ANALISIS.reset_index(inplace=True, drop=True)

In [61]:
DATASETS_ANALISIS

,Date,NOMBRE,AREA,TIPO,SECTOR,PRECIO,PRECIO NORMALIADO MAX,PRECIO NORMALIADO MIN,RENTABILIDAD SEMANAL,RENTABILIDAD MENSUAL,RENTABILIDAD ANUAL,RENTABILIDAD BIANUAL,RENTABILIDAD LUSTRO,A 6 MESES,A 1 ANIO,A 2 ANIOS,A 5 ANIOS
0,2022-03-06,DAX,EUROPA,INDICE,NaN,13087.13,809.848657,13.981976,-0.000566,-0.151570,-0.097588,0.417571,0.093951,NaN,NaN,NaN,NaN
1,2022-02-27,DAX,EUROPA,INDICE,NaN,13094.54,810.307197,13.989893,-0.101096,-0.132787,-0.059347,0.134525,0.088729,NaN,NaN,NaN,NaN
2,2022-02-20,DAX,EUROPA,INDICE,NaN,14567.23,901.439173,15.563280,-0.031596,-0.049071,0.056646,0.225130,0.234090,NaN,NaN,NaN,NaN
3,2022-02-13,DAX,EUROPA,INDICE,NaN,15042.51,930.850119,16.071058,-0.024804,-0.035976,0.074985,0.107751,0.279449,NaN,NaN,NaN,NaN
4,2022-02-06,DAX,EUROPA,INDICE,NaN,15425.12,954.526524,16.479829,0.021561,-0.028843,0.097882,0.122299,0.322119,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44519,2008-01-13,iShares Global Infrastructure ETF (IGF),EEUU,ETF,SERVICIOS PUBLICOS,46.15,925.591657,2.169723,-0.048061,-0.073851,NaN,NaN,NaN,-0.035320,-0.407367,-0.235970,-0.216901
44520,2008-01-06,iShares Global Infrastructure ETF (IGF),EEUU,ETF,SERVICIOS PUBLICOS,48.48,972.322503,2.279267,-0.015834,NaN,NaN,NaN,NaN,-0.048061,-0.402847,-0.264233,-0.255363
44521,2007-12-30,iShares Global Infrastructure ETF (IGF),EEUU,ETF,SERVICIOS PUBLICOS,49.26,987.966306,2.315938,-0.012034,NaN,NaN,NaN,NaN,-0.015834,-0.386724,-0.308161,-0.265327
44522,2007-12-23,iShares Global Infrastructure ETF (IGF),EEUU,ETF,SERVICIOS PUBLICOS,49.86,1000.000000,2.344147,0.000602,NaN,NaN,NaN,NaN,-0.012034,-0.432812,-0.310068,-0.295828
44523,2007-12-16,iShares Global Infrastructure ETF (IGF),EEUU,ETF,SERVICIOS PUBLICOS,49.83,999.398315,2.342736,NaN,NaN,NaN,NaN,NaN,0.000602,-0.410997,-0.307646,-0.288782

In [62]:
DATASETS_ANALISIS.set_index("Date", inplace=True)

In [66]:
pd.set_option("display.max_rows", 9999)

In [70]:
DATASETS_ANALISIS.head()

,NOMBRE,AREA,TIPO,SECTOR,PRECIO,PRECIO NORMALIADO MAX,PRECIO NORMALIADO MIN,RENTABILIDAD SEMANAL,RENTABILIDAD MENSUAL,RENTABILIDAD ANUAL,RENTABILIDAD BIANUAL,RENTABILIDAD LUSTRO,A 6 MESES,A 1 ANIO,A 2 ANIOS,A 5 ANIOS
Date,,,,,,,,,,,,,,,,
2022-03-06,DAX,EUROPA,INDICE,NaN,13087.13,809.848657,13.981976,-0.000566,-0.151570,-0.097588,0.417571,0.093951,NaN,NaN,NaN,NaN
2022-02-27,DAX,EUROPA,INDICE,NaN,13094.54,810.307197,13.989893,-0.101096,-0.132787,-0.059347,0.134525,0.088729,NaN,NaN,NaN,NaN
2022-02-20,DAX,EUROPA,INDICE,NaN,14567.23,901.439173,15.563280,-0.031596,-0.049071,0.056646,0.225130,0.234090,NaN,NaN,NaN,NaN
2022-02-13,DAX,EUROPA,INDICE,NaN,15042.51,930.850119,16.071058,-0.024804,-0.035976,0.074985,0.107751,0.279449,NaN,NaN,NaN,NaN
2022-02-06,DAX,EUROPA,INDICE,NaN,15425.12,954.526524,16.479829,0.021561,-0.028843,0.097882,0.122299,0.322119,NaN,NaN,NaN,NaN

In [72]:
DATASETS_ANALISIS.to_csv("DATASETS_analisis.csv", index = True)